name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: build
        working-directory: ${{github.workspace}}/src
        run: make
        
  check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: check_style
        working-directory: ${{github.workspace}}/src
        run: make check_style
        
  unit-test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: install google test
        run: sudo apt-get install libgtest-dev
      
      - name: tests
        working-directory: ${{github.workspace}}/src
        run: make test
  
